### ISSUE TITLE
Make a UI for home section

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#11]
Realate Home page or Welcome Page. 

This will be the first page shown in the application with some description of the application with images. 
Make it responsive with a rich user interactivity for the viewers. Create a separate folder for the component in components folder containing the home page js file , css files and export it as a default component. Use modular CSS for stylings.

Use reusable Prediction Card component and button component.

![RealateHome2](https://user-images.githubusercontent.com/50537259/104911931-a0fdc080-59b1-11eb-91f8-64fbdeef0447.png)

**Comment by Sloth-Panda** [comment]
What is the tech stack you want to use if html, css, js then i can take this issue

**Comment by 07souravkunda** [comment]
> What is the tech stack you want to use if html, css, js then i can take this issue

You have to work on react

**Comment by Abhir-24** [comment]
@07souravkunda I can work on this issue for SWOC. Also should I make a PR after 4 jan for it to be counted?

**Comment by sanjay270899** [comment]
I would like to work on this.

**Comment by kahanikaar** [comment]
> @07souravkunda I can work on this issue for SWOC. Also should I make a PR after 4 jan for it to be counted?

You can work on it now, scoring for DWOC is already going on, whereas for SWOC, the scoring will start from 4th of Jan

**Comment by kahanikaar** [comment]
> What is the tech stack you want to use if html, css, js then i can take this issue

WIll you be able to work on the issue, or shall I assign it to @Abhir-24

**Comment by sakshikhachane** [comment]
@kahanikaar Can I work on this issue if available?

**Comment by Kathuria** [comment]
@kahanikaar : Can you please assign this issue - As tech stack is react So @Sloth-Panda might won't work on this!
