### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#12]
Create a navigation bar for the application. 
This navigation bar must be displayed as fixed and must be responsive in the site. At the time of navigation pages should appear with slide from right transition effect.

**Comment by sanjay270899** [comment]
I want to work on this.

**Comment by 07souravkunda** [comment]
@sanjay270899 You can start working on this

**Comment by sanjay270899** [comment]
What will be the content and color of the navbar?

**Comment by 07souravkunda** [comment]
Take some dummy navlinks for now. Logo(take dummy for now) of the application will be on left side and navs on right side.
Color will be decided after homepage is ready. Take some random color for now.
It should be responsive.

**Comment by sanjay270899** [comment]
Your discord ID? So that I can contact you with any doubt. I have message "Hi" in the realate channel of DWOC server.

**Comment by 07souravkunda** [comment]
Sourav_kunda this is my discord id. Feel free to contact for any doubts.

**Comment by sanjay270899** [comment]
Which branch I have to consider?

**Comment by 07souravkunda** [comment]
development branch. CONTRIBUTING.md file is added visit for guidelines.
