### ISSUE TITLE
Signin/Signup components frontend

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#13]
An interactive & fully responsive signup/ registration form along with proper validations for signup and signin of users. 
Fields for signup - name(required), email(normal email validation),mobile no (10 digit number),address(required), password(more than 6 characters). User will signin using email and password.

![RealateSignIn](https://user-images.githubusercontent.com/50537259/104116866-69a06b80-5342-11eb-977a-d179d0692566.png)

![RealateSignUp](https://user-images.githubusercontent.com/50537259/104116877-76bd5a80-5342-11eb-93ed-a68c8664fe91.png)

**Comment by vinishhub** [comment]
I want to do this

**Comment by ritikchinu** [comment]
I want to do this, I am a swoc participant and have worked on something similar to this

**Comment by 07souravkunda** [comment]
> I want to do this, I am a swoc participant and have worked on something similar to this

@ritikchinu this issue is already assigned

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by sanjay270899** [comment]
Have you made any designs?
Where should I add the Login and SignUp components?

**Comment by 07souravkunda** [comment]
Basic design will be shared soon. You can start working after that.

**Comment by dollyjain51099** [comment]
I would like to work on this issue, please assign it to me!

**Comment by sanyajain26** [comment]
I would like to work on this issue, please assign it to me.

**Comment by AbhipsaGuru1012** [comment]
I would like to work on this. Can you please assign me this issue?

**Comment by 07souravkunda** [comment]
@sanjay270899 Just create the signin and signup components. No need to create the whole page. Place component files inside compnents/auth folder.
