### ISSUE TITLE
JWT Authentication Backend

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#14]
Create a robust authentication flow using jwt. 

Need to create User Model with name(required), email(normal email validation),mobile no (10 digit number),address(required), password(more than 6 characters). Controller methods for signing in user, signing up user. Models should be placed in model folder and controller methods in authenticationController.js file in controller folder.

Technologies:
Database : MongoDB

Code Structure: 
Create user model named as createModel.js and place it in models folder. Follow resourceModel.js.
Create authenticationController.js file in controller folder.
An error handling approach is already there. Follow it by refering to resourceController.js file.
Export all methods from authenticationConttoller as objects.
Place all routes for authentication in authenticationRoutes.js inside routes folder.

**Comment by ritikchinu** [comment]
I would to work on this, I am an swoc participant

**Comment by ritikchinu** [comment]
@07souravkunda please unassign this issue as i already got another issue assigned to me in another project

**Comment by 07souravkunda** [comment]
ok

**Comment by sanjay270899** [comment]
I would like to work on this.

**Comment by kahanikaar** [comment]
Assigned to @sanjay270899
