### ISSUE TITLE
Correction in README.md

### ISSUE THREAD

**Issue by Khimit** [deluminators/Realate#17]
In features ->land cover -> first line -> word **'int'** should be changed to **'it'**
![Capture](https://user-images.githubusercontent.com/46605529/103274667-37a91400-49e8-11eb-910e-a03314e7d230.PNG)
**.

**Comment by Khimit** [comment]
I would like to work on this.
please assign this to me.

**Comment by kahanikaar** [comment]
Closing issue as not as per contributing guidelines. 
Post suggestions on discussions thread.
