### ISSUE TITLE
Readme can be updated like adding different programs that this project is a part of

### ISSUE THREAD

**Issue by Sloth-Panda** [deluminators/Realate#23]
Like little description about SWOC and DWOC with their logo may be added after creating a new open-source section under readme

**Comment by Sloth-Panda** [comment]
Let me know if you want to add this or not. If interested please assign it to me

**Comment by kahanikaar** [comment]
Yes you can start working on it. Go ahead. Assigning to @Sloth-Panda

**Comment by kahanikaar** [comment]
Closing the issue.
