### ISSUE TITLE
Update: Update the datasets

### ISSUE THREAD

**Issue by sanjibansg** [deluminators/Realate#25]
### Requirement
Update the different datasets required for training and validation of machine learning models. Also propose for sources and newer sets required for better implementation of models.

**Comment by Cpt-Karthik** [comment]
I found some water cover images on [Kaggle](https://www.kaggle.com/franciscoescobar/satellite-images-of-water-bodies)
This dataset also contains mask (black and white) images for water bodies.

**Comment by kahanikaar** [comment]
Assigning to you @Cpt-Karthik

**Comment by SinghShreya05** [comment]
I'll like to work on this. Kindly assign me this issue @kahanikaar

**Comment by kahanikaar** [comment]
Assigning @SinghShreya05

**Comment by kahanikaar** [comment]
Update @SinghShreya05

**Comment by anirudhsai20** [comment]
Hi @kahanikaar . Can you please assign this to me under DWOC or SWOC?

**Comment by kahanikaar** [comment]
Go for it! Assigning to @anirudhsai20

**Comment by anirudhsai20** [comment]
Hi @kahanikaar . Can I further add more ctegoty of images? If yes, can I work on this under SWOC?

**Comment by kahanikaar** [comment]
> Hi @kahanikaar . Can I further add more categories of images? If yes, can I work on this under SWOC?

All contributions to the project are considered for both SWOC and DWOC. If you want to contribute more, update the branch you are working on with the new commits, the maintainers will review and merge.
