### ISSUE TITLE
Layout component frontend

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#38]
Create a react component named "Layout". This component will wrap all the pages of the application.

For styling refer to the image shown. On top of background image there is a backdrop with black fill and 0.4 opacity & a linear.

Place the component files inside components/layout folder. Use modular css for styling.

Find the background image in client/public/assets/LayoutBG.jpg

![RealateLayout](https://user-images.githubusercontent.com/50537259/104117076-2e9f3780-5344-11eb-9072-10fe61354e3a.png)

**Comment by sanjay270899** [comment]
I would Like to work on this. I am curious that how will other components come above it. Thank you!

**Comment by Kathuria** [comment]
I will be interested to work on this.

**Comment by Kathuria** [comment]
Thanks, starting my work.

**Comment by Kathuria** [comment]
Sample
![Sample](https://user-images.githubusercontent.com/19428377/104726146-22a6e180-5759-11eb-862b-f4227f268475.PNG)
