### ISSUE TITLE
React Reusable Button Component

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#42]
Create a reusable Button component.

Props passed,
 title,
 bgColor (default FF473A),
 textColor (default white),
 styles (to append additional styles)
 onClick

Styling is already done inside auth components SiginIn and SignUp. Find the button there and replace with reusable component.

![RealateSignIn](https://user-images.githubusercontent.com/50537259/104911323-b32b2f00-59b0-11eb-92ce-e6df5cc2e697.png)

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by sanjay270899** [comment]
We can close this issue if you wish.
