### ISSUE TITLE
React Reusable PredictionCard component

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#43]
Create a reusable prediction card component.

Props passed,
location,
img (link of the image),
styles (append additional styles),
width (default 30%),
id

![Group 5](https://user-images.githubusercontent.com/50537259/104913352-7b71b680-59b3-11eb-9224-277ffb334247.png)

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by Kathuria** [comment]
@07souravkunda : If issue is available to work, I can work on this
