### ISSUE TITLE
Create Auth page

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#51]
Use pre built signin and signup components to build an authentication page. Modify the styles of these components if necessary.

![SigninRealate](https://user-images.githubusercontent.com/50537259/105689430-c4c88580-5f20-11eb-80e4-a3f777289eba.png)
![SignUpRealate](https://user-images.githubusercontent.com/50537259/105689443-c8f4a300-5f20-11eb-8434-5fddd48c51a0.png)

Refer below for css,

[get design](https://drive.google.com/drive/folders/16rI9nEmTb0AWpehPDtxzlDMB_WmztgzP?usp=sharing)

**Comment by kenkirito** [comment]
assign me

**Comment by sanjay270899** [comment]
I would Like to work on this.
