### ISSUE TITLE
Populate predictions on homepage

### ISSUE THREAD

**Issue by 07souravkunda** [deluminators/Realate#52]
Render prediction cards on home page.

![RealateHome2](https://user-images.githubusercontent.com/50537259/105697231-51c40c80-5f2a-11eb-80bf-948c455a3751.png)

Refer below for the css,

[Get design](https://drive.google.com/drive/folders/16rI9nEmTb0AWpehPDtxzlDMB_WmztgzP?usp=sharing)

**Comment by kenkirito** [comment]
assign me

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by sanjay270899** [comment]
@07souravkunda Can I work on this issue?

**Comment by kahanikaar** [comment]
Update @kenkirito

**Comment by kenkirito** [comment]
Sorry I forgot about this summiting the pr by tomorrow. Thank you

**Comment by sanjay270899** [comment]
Now can I work on this issue?

**Comment by kenkirito** [comment]
@sanjay270899 you can go ahead I am busy in some work

**Comment by anirudhsai20** [comment]
Hi @sanjay270899 . Can you please assign me this issue under DWOC or SWOC?

**Comment by sanjay270899** [comment]
@kahanikaar @07souravkunda I think we should close this issue.
